import re

with open('src/data/randomizer_data.h', 'r') as f:
    content = f.read()

# Find the species entries
pattern = re.compile(r'(\d+),\s*//\s*(SPECIES_\w+)\s*\(BST:\s*(\d+)\)')
matches = pattern.findall(content)

if not matches:
    print("No matches found!")
    exit(1)

# Reconstruct the file with ONLY the sorted pool
new_content = "// Generated by Antigravity - Pre-sorted BST data\n"
new_content += f"#define NUM_VALID_SPECIES {len(matches)}\n\n"
new_content += "const u16 gSortedSpeciesPool[NUM_VALID_SPECIES] = {\n"

for species_id, species_name, bst in matches:
    new_content += f"    {species_id}, // {species_name} (BST: {bst})\n"

new_content += "};\n"

with open('src/data/randomizer_data.h', 'w') as f:
    f.write(new_content)

print(f"Successfully processed {len(matches)} species into lean header.")
